server:
  port: 8100
spring:
  application:
    name: TwinsBufferPool
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
logging:
  level:
    com:
      dx: debug
buffer:
  allow-duplicate: false
  capacity: 1000
  threshold: 0.8
  pool:
    enable-temporary-storage: true
    buffer-time-in-seconds: 60
---
spring:
  profiles:
    active: dev